/**
 * Website Cloner Pro - Extension Configuration
 *
 * This file is automatically generated during the build process.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * To set the API URL for production:
 * 1. Set VITE_API_URL environment variable
 * 2. Run: npm run build:extension
 *
 * For development, the default localhost URL is used.
 */

// Environment configuration
// __ENV__ and __API_BASE_URL__ are replaced during build
const ENV = '__ENV__';
const API_BASE_URL = '__API_BASE_URL__';

// Detect if this is a development build (placeholders not replaced)
const isDevelopment = ENV === '__ENV__' || ENV === 'development';

// Export configuration
export const config = {
  // Environment: 'development' or 'production'
  environment: isDevelopment ? 'development' : ENV,

  // API base URL
  apiBaseUrl: isDevelopment ? 'http://localhost:3000/api' : API_BASE_URL,

  // Debug mode
  debug: isDevelopment,

  // Extension version (from manifest)
  version: chrome.runtime.getManifest().version,

  // Feature flags
  features: {
    // Enable console logging in development
    logging: isDevelopment,

    // Enable detailed error messages
    verboseErrors: isDevelopment,

    // Enable performance monitoring
    performanceMonitoring: !isDevelopment,
  },
};

// Log configuration on load (development only)
if (config.debug) {
  console.log('Extension Configuration:', {
    environment: config.environment,
    apiBaseUrl: config.apiBaseUrl,
    version: config.version,
  });
}

// Freeze configuration to prevent accidental modifications
Object.freeze(config);
Object.freeze(config.features);
