-- Seed: Default Key Rotation Schedules
-- Description: Creates default encryption key rotation schedules

-- Insert default rotation schedules
INSERT INTO key_rotation_schedule (
  schedule_name,
  rotation_type,
  rotation_interval_days,
  next_rotation_at,
  is_active,
  auto_rotate,
  notification_email
) VALUES
  (
    'User Data Encryption Keys - Quarterly',
    'user_data',
    90,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    true,
    true,
    'security@example.com'
  ),
  (
    'Session Encryption Keys - Monthly',
    'session_data',
    30,
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    true,
    true,
    'security@example.com'
  ),
  (
    'File Encryption Keys - Quarterly',
    'file_encryption',
    90,
    CURRENT_TIMESTAMP + INTERVAL '90 days',
    true,
    true,
    'security@example.com'
  ),
  (
    'API Token Encryption Keys - Bi-Annual',
    'api_tokens',
    180,
    CURRENT_TIMESTAMP + INTERVAL '180 days',
    true,
    true,
    'security@example.com'
  ),
  (
    'Backup Encryption Keys - Annual',
    'backup_data',
    365,
    CURRENT_TIMESTAMP + INTERVAL '365 days',
    true,
    false,
    'security@example.com'
  )
ON CONFLICT DO NOTHING;

-- Note: Actual encryption keys will be generated by the application
-- This seed only creates the rotation schedules
